DATAPATH= "Data"
PLOT_PATH= f"{DATAPATH}/Plots"
RESULTS_PATH= f"{DATAPATH}/Results"
MODEL_PATH= f"{DATAPATH}/Models"

MONK_PLOT_PATH= f"{PLOT_PATH}/Monk"
MONK_RESUTL_PATH= f"{RESULTS_PATH}/Monk"
MONK_MODEL_PATH= f"{MODEL_PATH}/Monk"

CUP_PLOT_PATH= f"{PLOT_PATH}/Cup"
CUP_RESULTS_PATH= f"{RESULTS_PATH}/Cup"
CUP_MODEL_PATH= f"{MODEL_PATH}/Cup"