DATAPATH= "Data"
PLOTPATH= f"{DATAPATH}/Plots"
RESULTSPATH= f"{DATAPATH}/Results"
MODELPATH= f"{DATAPATH}/Models"

MONKPLOTPATH= f"{PLOTPATH}/Monk"
MONKRESUTLPATH= f"{RESULTSPATH}/Monk"
MONKMODELPATH= f"{MODELPATH}/Monk"

CUPPLOTPATH= f"{PLOTPATH}/Cup"
CUPRESULTSPATH= f"{RESULTSPATH}/Cup"
CUPMODELPATH= f"{MODELPATH}/Cup"