from Model import DATASET_PATH, PLOT_PATH, RESULTS_PATH, MODEL_PATH

MONK_PLOT_PATH= f"{PLOT_PATH}/Monk"
MONK_RESUTL_PATH= f"{RESULTS_PATH}/Monk"
MONK_MODEL_PATH= f"{MODEL_PATH}/Monk"
DATASET_PATH_MONK = f"{DATASET_PATH}/monks"



OPTIMIZER = 1

USE_KFOLD = False

KFOLD_NUM = 5
VAL_SPLIT = 0.15
DATA_SHUFFLE_SEED = 42

MONK_NUM= 1

DATASET_PATH_MONK_TR = f"{DATASET_PATH_MONK}/monks-{MONK_NUM}.train"
DATASET_PATH_MONK_TS = f"{DATASET_PATH_MONK}/monks-{MONK_NUM}.test"