from Model import PLOT_PATH, RESULTS_PATH, MODEL_PATH, DATASET_PATH

CUP_PLOT_PATH= f"{PLOT_PATH}/Cup"
CUP_RESULTS_PATH= f"{RESULTS_PATH}/Cup"
CUP_MODEL_PATH= f"{MODEL_PATH}/Cup"
DATASET_PATH_CUP = f"{DATASET_PATH}/CUP"


USE_KFOLD = True
OPTIMIZER = 1
BATCH_SIZE = 128

DATASET_PATH_CUP_TR = f"{DATASET_PATH_CUP}/ML-CUP24-TR.csv"
DATASET_PATH_CUP_TS = f"{DATASET_PATH_CUP}/ML-CUP24-TS.csv"